# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8724623d9fcff3ad79f3101b11d4e462d1f1613b4906255a6dd14473e1f6a1f2d57268ffe028021882df097ad8857bbf6ec7e601eafba1af35b6cc638818610

test:
  secret_key_base: 348bfdf724663b886222f8a36634241ca96a85fedaecba8390775c8508975a40e24550c193b56641c3e08d66d2f800860bda53c93bd7de2931206572430e52dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
